### ISSUE TITLE
[Feat] 대표이미지 API 및 도장 이미지 반영 방법 변경

### ISSUE THREAD

**Issue by khwoowoo** [UMC-5th-Coumo/server#103]
# ⚙️ ISSUE
- 대표이미지 API 및 도장 이미지 반영 방법 변경

# 📄 To-Do
- [x] 대표 이미지 API 생성
- [x] S3에 도장 이미지 5개 넣기
- [x] 정적 클래스 만든 후, map에 도장 이미지 url 반영하여 앱에게 전달하도록 하기
