### ISSUE TITLE
[Fix] 변경된 도메인 및 기획에 맞게 수정

### ISSUE THREAD

**Issue by khwoowoo** [UMC-5th-Coumo/server#62]
# ⚙️ ISSUE
- 기획 내용에서 커스텀 쿠폰에 대한 방법이 달라진 것에 따라
- 가게 조회시 쿠폰에 대한 정보를 수정
- 가게 정보 작성 여부 로직 작성

# 📄 To-Do
- [ ] 가세 상세 조회 DTO 수정
- [ ] 수정 내용 테스트하기
- [ ] 가게 정보 작성 여부 로직 작성
