### ISSUE TITLE
[Feat] QR을 이용한 도장 적립/사용 API

### ISSUE THREAD

**Issue by proysm** [UMC-5th-Coumo/server#64]
# 🛠️ ISSUE
APP(사장) QR 인식
APP(고객) 도장 적립/사용 QR 생성

# 📑 To-Do

- [x] 고객 : 도장 **적립** QR 생성
- [x]  고객 : 도장 **사용** QR 생성
- [x]  사장 : QR 인식 
- [x]  사장 : QR 인식 후 적립 **도장 개수 입력**
