### ISSUE TITLE
[Fix] 로그인, 인증번호 관련 코드 수정 WEB&APP

### ISSUE THREAD

**Issue by junggyo1020** [UMC-5th-Coumo/server#86]
# ⚙️ ISSUE
- 로그인 및 인증번호 관련 코드 수정 WEB

# 📄 To-Do

- [x] 로그인 시 ownerId, storeId, token, 최초로그인 여부, 서비스 가입날짜, name, loginId, email, phone 반환하도록 수정
- [x] 마이페이지 - 내 프로필 조회 api 삭제
- [x] 아이디 찾기 - 인증번호 검증 API 오류 수정
- [x] 회원가입 시 customer 및 owner의 State값 ACTIVE 로 기본 설정
