### ISSUE TITLE
[Feat] 로그아웃 & 회원탈퇴 기능 구현 WEB&APP

### ISSUE THREAD

**Issue by junggyo1020** [UMC-5th-Coumo/server#90]
# ⚙️ ISSUE
- 로그아웃 & 회원탈퇴 기능 구현 WEB&APP

# 📄 To-Do

- [x] 로그아웃 기능 구현 WEB
- [x] 로그아웃 기능 구현 APP
- [x] 회원탈퇴 기능 구현 WEB
- [x] 회원탈퇴 기능 구현 APP
